import {createSlice} from "@reduxjs/toolkit"

const productSlice = createSlice({
    name:'product',
    initialState:{
        loading:false,
        product:{},
        isReviewSubmitted:false,
        isProductCreated:false
    },
    reducers:{
        productRequest(state,action){
            return{
                ...state,
                loading:true
            }
        },
        productSuccess(state,action){
            return{
                ...state,
                loading:false,
                product:action.payload.product
            }
        },
        productFail(state,action){
            return{
                ...state,
                loading:false,
                error:action.payload
            }
        },
        createReviewRequest(state,action){
            return{
                ...state,
                loading:true
            }
        },
        createReviewSuccess(state,action){
            return{
                ...state,
                loading:false,
                isReviewSubmitted:true
            }
        },
        createReviewFail(state,action){
            return{
                ...state,
                loading:false,
                error:action.payload
            }
        },
        clearReviewSubmitted(state,action){
            return{
                ...state,
                isReviewSubmitted:false
            }
        },
        clearError(state,action){
            return{
                ...state,
                error:null
            }
        },
        clearProduct(state,action){
            return{
                ...state,
                product:{}
            }
        },
        NewProductRequest(state,action){
            return{
                ...state,
                loading:true
            }
        },
        NewProductSuccess(state,action){
            return{
                ...state,
                loading:false,
                isProductCreated:true,
                product:action.payload.product
            }
        },
        NewProductFail(state,action){
            return{
                ...state,
                loading:false,
                error:action.payload
            }
        },
        clearProductCreated(state,action){
            return{
                ...state,
                isProductCreated:false
            }
        }

    }
});

const {actions , reducer}=productSlice;

export const {
    productRequest,
    productSuccess,
    productFail,
    createReviewFail,
    createReviewSuccess,
    createReviewRequest,
    clearError,
    clearReviewSubmitted,
    clearProduct,
    NewProductSuccess,
    NewProductRequest,
    NewProductFail,
    clearProductCreated
}=actions;

export default reducer;